# Generated by Django 2.2.4 on 2020-03-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback_System', '0002_auto_20200301_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaches',
            name='semester',
            field=models.IntegerField(choices=[(1, 1), (2, 2)], default=1),
        ),
        migrations.AlterField(
            model_name='teaches',
            name='year',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=1),
        ),
    ]
