# Generated by Django 2.2.5 on 2020-02-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback_System', '0002_studentprofile_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='semester',
            field=models.IntegerField(default=1),
        ),
    ]
